spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/instagram
        username: postgres
        password: postgres
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true

#    flyway:
#        baseline-on-migrate: true
#        enabled: true
#        locations: "classpath:migration"